version: 2.1

executors:
  node:
    parameters:
      image:
        type: string
        default: "14"
    docker:
      - image: circleci/node:<< parameters.image >>
        environment:
          TERM: xterm

aliases:
  restore_cache: &restore_cache
    restore_cache:
      name: Restore NPM Package Cache
      keys:
        # Find a cache corresponding to this specific package-lock.json
        - dependencies-{{ .Environment.CIRCLE_CI_CACHE_VERSION }}{{ checksum "package-lock.json" }}
        # Fallback cache to be used
        - dependencies-{{ .Environment.CIRCLE_CI_CACHE_VERSION }}

  install_node_modules: &install_node_modules
    run:
      name: Install NPM Packages
      command: npm install --frozen-lockfile

  save_cache: &save_cache
    save_cache:
      name: Save NPM Package Cache
      key: dependencies-{{ .Environment.CIRCLE_CI_CACHE_VERSION }}{{ checksum "package-lock.json" }}
      paths:
        - node_modules

jobs:
  install:
    executor: node
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *save_cache

  deploy-gh:
    executor: node
    steps:
      - checkout
      - <<: *restore_cache
      - run: git config user.email "ci-build@ohmybuck.com"
      - run: git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "d4:89:c8:ec:80:cf:e0:b7:4e:71:16:46:45:c5:2a:db"
      - run: npm run deploy

workflows:
  version: 2.1
  test:
    jobs:
      - install:
          filters:
            branches:
              ignore:
                - gh-pages
                - master

  build:
    jobs:
      - install:
          filters:
            branches:
              only:
                - master
      - deploy-gh:
          requires:
            - install
